development:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  encoding: unicode
  adapter: postgresql
  username: xzdsaqoipskcmm
  port: 5432
  host: ec2-184-73-251-115.compute-1.amazonaws.com
  database: d86131glavkre
  password: oyyeLl-D-GBxoqVBZK127bqynu